version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    pull-request-branch-name:
      separator: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Group dependency updates by type
    groups:
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
    # Be cautious with major version updates for critical dependencies
    ignore:
      - dependency-name: "pa11y"
        update-types: ["version-update:semver-major"]
      - dependency-name: "puppeteer"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    pull-request-branch-name:
      separator: "/"    
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "02:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"

  # Enable version updates for Docker (if Dockerfile exists)
  - package-ecosystem: "docker"
    directory: "/"
    pull-request-branch-name:
      separator: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "docker"
      include: "scope"
